### ISSUE TITLE
Pulling Magento 2 OpenAPI spec version 2.4.6 seems to contain an error

### ISSUE THREAD

**Issue by SwissMaWi** [AdobeDocs/commerce-webapi#141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://developer.adobe.com/commerce/webapi/rest/quick-reference/

### What's wrong with the content?

Current and previous versions of the OpenAPI specification have multiple errors. 
Many nullable fields are not marked as nullable.
But the biggest problem is:
Open the swagger.json with Swagger Online Editor
![image](https://github.com/AdobeDocs/commerce-webapi/assets/46742945/08d3c5ce-1ea7-4b26-94ae-638c0838ec88)

### What changes do you propose?

Correct the spec

**Comment by SwissMaWi** [comment]
Does it make any sense to send a body with a delete request?

**Comment by jhadobe** [comment]
As @jeff-matthews said this appears to be an issue of versioning. The hosted schema is automatically converted from [`swagger: "2.0"`](https://github.com/AdobeDocs/commerce-webapi/blob/229b515a2ab37e9880ccb806e4c5ff22366b3123/src/openapi/admin-schema-2.4.6.yaml#L6) on GitHub to `"openapi": "3.0.0"` when downloaded from our hosted site. I did not find a way to allow older OpenAPI specifications on our host.

The change to 3.0.0 means that `DELETE` requests are not allowed to have bodies:

```
GET, DELETE and HEAD are no longer allowed to have request body because it does not have defined semantics as per [RFC 7231](https://tools.ietf.org/html/rfc7231#section-4.3).
https://swagger.io/docs/specification/describing-request-body/
```

Alternatively, we could replace [`in: body`](https://github.com/AdobeDocs/commerce-webapi/blob/229b515a2ab37e9880ccb806e4c5ff22366b3123/src/openapi/admin-schema-2.4.6.yaml#L18332) with `in: path`, but we would need to manually do this every time the schema is updated. 

As @SwissMaWi indicated, my understanding is that `DELETE` requests do not need a body, but there could be some edge case that I am unaware of. Additionally, this error is only visible when downloaded and pasted into an editing tool like: https://editor.swagger.io.

I would like to hear @keharper's thoughts on this.

**Comment by keharper** [comment]
This is an issue with the code base. We just run the `GET http://<host_name>/rest/default/schema` call to extract the schema and do some reformatting to make the presentation better for ReDoc. The issues you are seeing have always existed, AFAIK. Please open a ticket against the [magento2 repo](https://github.com/magento/magento2).

**Comment by SwissMaWi** [comment]
No time for that… and if old bugs means that they are good bugs… you are definitely not in my world of quality software. Byebye

Von: Kevin Harper ***@***.***>
Gesendet: Montag, 26. Juni 2023 23:24
An: AdobeDocs/commerce-webapi ***@***.***>
Cc: Martin Widmer-Phutadon ***@***.***>; Mention ***@***.***>
Betreff: Re: [AdobeDocs/commerce-webapi] Pulling Magento 2 OpenAPI spec version 2.4.6 seems to contain an error (Issue #141)


This is an issue with the code base. We just run the GET http://<host_name>/rest/default/schema<http://%3chost_name%3e/rest/default/schema> call to extract the schema and do some reformatting to make the presentation better for ReDoc. The issues you are seeing have always existed, AFAIK. Please open a ticket against the magento2 repo<https://github.com/magento/magento2>.
