### ISSUE TITLE
Redocly REST API Schema Cannot be Downloaded

### ISSUE THREAD

**Issue by halostatue** [AdobeDocs/commerce-webapi#41]
### Expected Behaviour

I should be able to download the `schema.json` file(s) from https://magento.redoc.ly/. Ideally, I should be able to download the individual `schema.json` files *or* a unified `schema.json` file that contains all three schema definitions.

### Actual Behaviour

There are no schema download links at

- https://magento.redoc.ly/2.4.5-admin/
- https://magento.redoc.ly/2.4.5-customer/
- https://magento.redoc.ly/2.4.5-guest/

**Comment by jeff-matthews** [comment]
Thanks for the report @halostatue.

I'm not sure why, but we chose to hide the download button. It's easy enough to enable it though.

@jhadobe, I think all we need to do is update the `redocly.yml` config file in the repo that stores the schemas (not a public repo) and redeploy.

Specifically, by changing `hideDownloadButton: true` to `hideDownloadBbutton: false`.

**Comment by halostatue** [comment]
This and #42 are related in the sense that I do not necessarily trust that `http://<host>/rest/all/schema?services=all` is providing the complete schema—because the local swagger UI is not showing everything that’s in that schema and does not match the expected output. I’m l looking at this from a documentation perspective, but my interest is *mostly* in being able to use the schema for code generation via [OpenApi Generator](https://openapi-generator.tech).

The ability to download the *direct* source schema *and* a full schema would be appreciated, as it would provide a stable source for obtaining the Open API schema.

(As a separate question, where should possible issues with the schema definition *itself* go? We are seeing code that is generated correctly according to the specification, but the specification does not match the output from the install of Magento 2.4.x that we are running.)

**Comment by jeff-matthews** [comment]
Since the schema is generated from a running instance of magento, I recommend reporting possible issues with the schema itself in the the [magento/magento2](https://github.com/magento/magento2) repo.

**Comment by jhadobe** [comment]
@halostatue Download buttons should now be available. You may need to refresh your browser or clear your cache.
