### ISSUE TITLE
REST API Documentation is radically different between Redocly and Local

### ISSUE THREAD

**Issue by halostatue** [AdobeDocs/commerce-webapi#42]
### Expected Behaviour

I should see the same endpoints described at `http://<host>/swagger` (in some way) as I see at https://magento.redoc.ly, even though the generated shape will be different because of the difference between Swagger and ReDoc.

### Actual Behaviour

The documentation for [generating a local Schema reference](https://developer.adobe.com/commerce/webapi/rest/quick-reference/generate-local/) provides the `/swagger` URL which, if the store is not in `production` mode, should work and provide useful schema documentation. However, the schema (`http://<host>/rest/all/schema?services=all) and Swagger UI appear to have an entirely *different* set of generated UI and API descriptions than that provided via https://magento.redoc.ly (ignoring the different generators; from my local instance, I cannot find the admin API `/V1/customers/search`, but only `/V1/search`, in the Swagger UI).

This would be unnecessary if the various JSON schema files could be downloaded from https://magento.redoc.ly, as described in #41.

**Comment by jeff-matthews** [comment]
I think these differences come from the [post-processing](https://github.com/magento-devdocs/magento-openapi-transformer) that we do before we publish the schemas via Redocly.

CC: @keharper

**Comment by keharper** [comment]
@halostatue My local instances won't display Swagger, and so I can't drill down and try to debug your problem. I have to ask a basic question: are you providing an admin API key in your local Swagger instance? If memory serves correctly, Swagger doesn't always respond correctly when you hit the return key after copy/pasting your API key. Click the Enter button instead.

Our process for generating ReDoc is this:

1. Install a fresh instance of Adobe Commerce with B2B.
2. Extract the schemas for admin, customer, and guest users.
3. Process each schema a bit to allow for alphabetization and other minor tweaks.
4. Publish the modified schemas.

If you're using the 2.4.5 or 2.3.7 codebase, the schemas we publish should correspond with what you see locally, plus any extensions that add REST endpoints (and minus B2B/Commerce, if you didn't install them).

**Comment by halostatue** [comment]
That might be the issue (missing key). Ultimately what I’m wanting to do is make sure that I can get the complete schema (I *currently* need just admin, but will in the next couple of months need customer, so having a *single* schema for which I can generate code using OpenAPI Generator is best. I’m using the Swagger view as a proxy for what schema should be displaying. When I view the swagger UI, this is what I see:

![CleanShot 2022-09-29 at 14 43 19@2x](https://user-images.githubusercontent.com/11361/193116600-303a6d3b-7fb9-45b7-97ad-6299eb2278cc.png)

That’s a fraction of the APIs that I should be seeing. If I need to add an admin API key to fix that, I’m not sure what or where I can find that, whether it’s one of these or a computed version:

![CleanShot 2022-09-29 at 14 47 42@2x](https://user-images.githubusercontent.com/11361/193117141-5411ee6d-85e9-41aa-9b9b-d47d83e4989d.png)

The documentation on how to retrieve these and see the swagger output is vague on this part, which is part of why I’ve raised this issue. I *think* that I have the complete schema, but since I can’t get Swagger to agree with what I think I should be seeing, I’m not sure what the next steps are to see the correct thing.

**Comment by keharper** [comment]
@halostatue The API key that Swagger requires is the admin/customer authentication token. You have to specify one of those to get more than the bare bones schema you see by default. Generating this token is documented in multiple places, including [here](https://developer.adobe.com/commerce/webapi/get-started/authentication/gs-authentication-token/). If you're in a development environment and have managed to disable the security modules, you could also generate an admin token with `POST /V1/integration/admin/token`.

You will not be able to extract just the admin endpoints or just the customer endpoints. Magento doesn't work that way. If you provide an admin token, you'll get all the admin endpoints, plus the customer and guest endpoints. If you provide a customer token, you also get the guest endpoints.

**Comment by halostatue** [comment]
That works and it’s exactly what I was looking for. It would be useful to document the need for a token as part of the local Swagger documentation.
